/**
 * Created by Tongming on 2017/1/12.
 */
export const
	[REQUEST_DATA, RECEIVE_DATA, REQUEST_FAIL,
		HOME, BANNER_CHANGED, CATEGORY, SEARCH, SEARCH_CHANGE,
		DETAIL, PAGE, CHANGE_PAGE, CONTROLLER, COLLECTION, USER,
		SCROLL_BAR, INIT_IMAGE, DRAW_LAYOUT]
		=
		['REQUEST_DATA', 'RECEIVE_DATA', 'REQUEST_FAIL',
			'HOME', 'BANNER_CHANGED', 'CATEGORY', 'SEARCH',
			'SEARCH_CHANGE', 'DETAIL', 'PAGE', 'CHANGE_PAGE', 'CONTROLLER',
			'COLLECTION', 'USER', 'SCROLL_BAR', 'INIT_IMAGE', 'DRAW_LAYOUT'];